export const SEARCHCHANGED = 'SEARCHCHANGED';
export const AUTHORCHANGED = 'AUTHORCHANGED';
export const AUTHORREMOVED = 'AUTHORREMOVED';
export const CATEGORYCHANGED = 'CATEGORYCHANGED';
export const CATEGORYREMOVED = 'CATEGORYREMOVED';